name: BuildBlock
version: 1.0.1
main: biz.yama2211.bb.Main

commands:
  buildblock:
    description: HelpCommand
  buildblock.reload:
    description: Config ReloadCommand

permissions:
  buildblock.ignore.break:
    description: 破壊の制限
    default: op
  buildblock.ignore.put:
    description: 設置の制限
    default: op
  buildblock.ignore.drop:
    description: 捨てることの制限
    default: op
  buildblock.ignore.pickup:
    description: 拾うことの制限
    default: op
  buildblock.ignore.bed:
    description: ベットに入ることの制限
    default: op
  buildblock.ignore.book:
    description: 本の編集することの制限
    default: op
  buildblock.ignore.bucket:
    description: バケツをぶちまけることの制限
    default: op

  buildblock.ignore.*:
    description: 制限系権限のすべて
    default: op
    children:
      buildblock.ignore.break: true
      buildblock.ignore.put: true
      buildblock.ignore.drop: true
      buildblock.ignore.pickup: true
      buildblock.ignore.book: true
      buildblock.ignore.bucket: true
  buildblock.admin:
    description: リロード
    default: op
